config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/dashboard_con_stimulus', to: 'dashboard#index'

  resources :reports, only: [:index]
  resources :candidate
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action -> { sleep 0 }
end

app/controllers/candidate_controller.rb
class CandidateController < ApplicationController
  include CableReady::Broadcaster

  def update
    Candidate.find(params[:id]).update(candidate_params)
    redirect_to dashboard_con_stimulus_path
  end

  def new
    @candidate = Candidate.new(status: 'pending')
  end

  def create
    candidate = Candidate.create(candidate_params)
    cable_ready["dashboard"].insert_adjacent_html(
      selector: "div.pending",
      position: "afterbegin",
      html: render_to_string(partial: "dashboard/candidate", locals: {candidate: candidate, next_status: 'interviewed'})
    )
    cable_ready.broadcast
    redirect_to new_candidate_path
  end

  private
  def candidate_params
    params.require(:candidate).permit(:name, :status)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @pending =     Candidate.where(status: 'pending'    ).order(updated_at: :desc).page(params['pending']    ).per(5)
    @interviewed = Candidate.where(status: 'interviewed').order(updated_at: :desc).page(params['interviewed']).per(5)
    @hired =       Candidate.where(status: 'hired'      ).order(updated_at: :desc).page(params['hired']      ).per(5)

    respond_to do |format|
      format.html
      format.json {
        render json: {
          pending: {
            entries: render_to_string(component: "Candidate", collection: @pending, locals: {next_status: 'interviewed'}, formats: [:html]),
            pagination: view_context.paginate(@pending, param_name: 'pending')
          },
          interviewed: {
            entries: render_to_string(partial: "candidate", collection: @interviewed, locals: {next_status: 'hired'}, formats: [:html]),
            pagination: view_context.paginate(@interviewed, param_name: 'interviewed')
          },
          interviewed: {
            entries: render_to_string(partial: "candidate", collection: @hired, locals: {next_status: 'archived'}, formats: [:html]),
            pagination: view_context.paginate(@hired, param_name: 'hired')
          }
        }
      }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidate/new.haml
= form_for(@candidate, url: candidate_index_path) do |f|
  = f.text_field :name
  = f.hidden_field :status
  = f.submit "Guardar"

app/views/dashboard/_candidate.haml
= react_component("Candidate", {name: candidate.name, status: candidate.status})

app/views/dashboard/_column.haml
%article.column{data: {controller: 'infinite-scroll', action: 'scroll->infinite-scroll#scroll', 'infinite-scroll-entities': current_status}}
  %h2= title
  .drag-item{data: {controller: 'drag-item', action: 'dragover->drag-item#dragover dragenter->drag-item#dragenter dragleave->drag-item#dragleave drop->drag-item#drop'}}
    %div.drop-zone{data: {target: 'infinite-scroll.entries'}, class: current_status}
      = render partial: "candidate", collection: collection, locals: { next_status: next_status}
    %div{data: {target: 'infinite-scroll.pagination'}}
      = paginate collection, param_name: current_status

app/views/dashboard/index.haml
.container
  = render partial: "column", locals: {title: "Pending",     collection: @pending,     current_status: 'pending',     next_status: 'interviewed'}
  = render partial: "column", locals: {title: "Interviewed", collection: @interviewed, current_status: 'interviewed', next_status: 'hired'}
  = render partial: "column", locals: {title: "Hired",       collection: @hired,       current_status: 'hired',       next_status: 'archived'}

app/views/home/index.haml
%h1 This is home

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Eudaemonia
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      Header
      %nav.main-nav
        %ul.navigation
          %li= link_to("Dashboard con Stimulus", dashboard_con_stimulus_path, data: {:"turbolinks-action" => "replace"})
          %li= link_to("Nuevo candidato", new_candidate_path, data: {:"turbolinks-action" => "replace"})
          %li= link_to("Reports", reports_path, data: {:"turbolinks-action" => "replace"})
      %p.notice= notice
      %p.alert= alert
    #main
      %article
        = yield
    %footer Footer

app/views/reports/index.haml
This is the report